### ISSUE TITLE
ngrx-immer is failing to build after release of latest version 

### ISSUE THREAD

**Issue by BhavyaGulaiah** [timdeschryver/ngrx-immer#30]
Hi Tim,

ngrx-immer is failing to build with the following error :
73.01 Error: node_modules/ngrx-immer/store/index.d.ts:1:22 - error TS6053: File '/app/node_modules/ngrx-immer/store/index.ngtypecheck.d.ts' not found.
73.01 
73.01 1 /// <reference path="index.ngtypecheck.d.ts" />

The version currently used in package.json is "^2.0.1".
The build is failing after the new major version 2.2.2.
Can you please let me know the dependencies.

**Comment by timdeschryver** [comment]
Hi @BhavyaGulaiah , I was unable to reproduce this.
Please provide a reproduction so I can take a closer look.

**Comment by nDaniel78** [comment]
After upgrading the Angular version to 18.1.0 and ngrx-immer to 2.2.2, I'm encountering this issue as well

**Comment by timdeschryver** [comment]
Please try again with v2.2.3
If the issue still occurs feel free to create a new issue with a reproduction.
