### ISSUE TITLE
immerPatchState is not working with "@ngrx/signals": "18.0.0-rc.3"

### ISSUE THREAD

**Issue by koempf** [timdeschryver/ngrx-immer#32]
immerPatchState(store, (state) => {
          state.form = {form: new FormGroup({}), template: c};
        });

(state) knows than only Object

state.form (Property form does not exist on type object)

**Comment by timdeschryver** [comment]
@koempf thanks for opening this issue.
This will be a breaking change (see #33).
